
# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0
---
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to write releases 

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set tag name
        shell: bash
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v3
        with:
          go-version-file: go.mod
          cache: false  
          check-latest: true
  
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1

      - name: Install bom
        uses: kubernetes-sigs/release-actions/setup-bom@8af7b2a5596dff526de9db59b2c4b8457e9f52a1 # v0.4.0

      - name: Generate SBOM
        shell: bash
        run: |
          bom generate --format=json -o /tmp/yamlplate-$TAG.spdx.json .

      - name: Publish Release
        uses: kubernetes-sigs/release-actions/publish-release@8af7b2a5596dff526de9db59b2c4b8457e9f52a1 # v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assets: "/tmp/yamlplate-$TAG.spdx.json"
          sbom: false
